### ISSUE TITLE
RoaringBitset deserialization does not work

### ISSUE THREAD

**Issue by KarolKolenda** [BitSetsNet/BitSetsNet#49]
I am having a trouble with deserialization of RoaringBitset. Serialization seems to be OK, as output stream is not empty and have the same size to other roaring bitmap implementation. But deserialization does not seem to work. Please find the following test case:

```
        RoaringBitset expected = new RoaringBitset();
        expected.add(1);

        MemoryStream stream = new MemoryStream();
        expected.Serialize(stream);

        stream.Position = 0;

        var actual = RoaringBitset.Deserialize(stream);
        if (expected.Get(1) != actual.Get(1))
        {
            throw new SerializationException();
        }
```

**Comment by oahassan** [comment]
I've got a fix for this coming up. This functionality doesn't have test coverage yet, and so was liable to have some kind of problem.

**Comment by KarolKolenda** [comment]
@oahassan Thank you for the update. Great work btw!

**Comment by BitSetsNet** [comment]
This duplicates Issue #18. Since this has more detail I'll close that one.

**Comment by jaredvonhalle** [comment]
This should be fixed now
