### ISSUE TITLE
RLEBitset's Set method changes the length

### ISSUE THREAD

**Issue by andersstorhaug** [BitSetsNet/BitSetsNet#70]
Example:

```
var bitset = RLEBitset.CreateFrom(new int[] { }, 100);

var beforeLength = bitset.Length(); // 100
bitset.Set(0, true);
var afterLength = bitset.Length(); // 1
```

The reason that this is problematic for me, is that `Set` calls breaks subsequent set operations against other bitsets that should be the same length.

My current workaround is as follows:
```
public static class RLEBitsetExtensions
{
    public static void SetWithLength(this RLEBitset bitset, int index, bool value)
    {
        if (value)
        {
            bitset.OrWith(RLEBitset.CreateFrom(new[] { index }, Math.Max(bitset.Length(), index + 1)));
        }
        else
        {
            bitset.DifferenceWith(RLEBitset.CreateFrom(new[] { index }, Math.Max(bitset.Length(), index + 1)));
        }
    }
}
```

On another note - I realize that RLE compressed bitsets are probably not the primary focus of this library, but I think I have a use for them, so I wanted to leverage what you had here.

**Comment by paul-mannino** [comment]
I'll look into this later tonight. You're also more than welcome to submit a PR if you'd like.

**Comment by andersstorhaug** [comment]
Playing around with it some more, this issue only seems to occur when `Set` is called on a `RLEBitset` with no runs (but still with a length > 0).
