### ISSUE TITLE
RoaringBitset.Set(int start, int end, bool value) is inconsistent

### ISSUE THREAD

**Issue by tesfabpel** [BitSetsNet/BitSetsNet#72]
Sometimes using RoaringBitset.Set(int start, int end, bool value) gives wrong results depending on the values of `start` and `end`...
The same call with RLEBitset works....

![bug](https://user-images.githubusercontent.com/1371976/28721202-cad35fd2-73af-11e7-80be-0d61c8e3ce69.png)

**Comment by paul-mannino** [comment]
Thanks for the report! Opened a PR for this.
